= Graduaatsproef 


== Percistence (Sören)

=== Databank diagram

=== Aanmelden van bezoeker (Leg uit waarom we transacties gebruiken)

=== Het Updaten van gegevens (Leg uit waarom we eigenlijk geen update doen maar met een isActief colom werken)

== Presentatie (Noah, Tuur)

=== ILijstItem Interface (Leg uit waarom we een ILijstInterface hebben)

==== Doel
De interface ILijstItem wordt gebruikt wanneer je een object wilt presenteren in een combobox (lijst).

==== Werking
*Voorbeeld*
Stel dat we het object Bedrijf in een combobox willen tonen. We beginnen met de interface te implimenteren.
ILijstItem Heeft 2 properties:


----
 public class BedrijfView : ILijstItems
    {
        public Bedrijf Bedrijf;
        private string _naam;
        private string _btw;

        ...

        // Lijst items
        public string Id { get => Email; }
        public string ItemNaam { get => Naam; }
----


Vervolgens kunnen we nu een combobox maken met de bedrijven als data.
----
<UIC:ZoekbareComboBox x:Name="bedrijfComboBox"/> 
----
----
List<ILijstItems> bedrijfItems = bedrijven.Select(x => (ILijstItems)new BedrijfView(x)).ToList();
bedrijfComboBox.VoegLijstToe(bedrijfItems);
----

Hier wordt de combobox ingesteld.
----

public partial class ZoekbareComboBox : UserControl
    {
        ...

        public void VoegLijstToe(List<ILijstItems> items)
                {
                    comboBox.Items.Clear();
                    _alleItems = items;
                    foreach (ILijstItems item in items)
                    {
                        comboBox.Items.Add(item.ItemNaam);
                    }
                }

        ...
----
Door deze interface te gebruiken kunnen we nu bij het klikken van een bedrijf een id mee krijgen.
----
        ...

        private void comboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
                {
                    if ((e.AddedItems.Count > 0))
                    {
                        int SelectedIndex = comboBox.SelectedIndex;
                        SelectedValue = _alleItems[SelectedIndex].Id;  <-- Hier wordt de Id gegeven
                        SelectedLabel = _alleItems[SelectedIndex].ItemNaam;
                        if (GeSelecteerd != null)
                        {
                            GeSelecteerd.Invoke(this, SelectedValue);
                        }
                    }
                }

        ...
----

We kunnen ook een filter methode toepassen.
----
        ...

        List<ILijstItems> result = new List<ILijstItems>();
                    foreach (ILijstItems w in _alleItems)
                    {
                        string woord = w.ItemNaam;
                        bool gevonden = true;
                        if (zoekwoord.Length <= woord.Length)
                        {
                            for (int i = 0; i < zoekwoord.Length; i++)
                            {
                                if (Char.ToLower(zoekwoord[i]) == Char.ToLower(woord[i]))
                                {
                                    gevonden = true;
                                }
                                else
                                {
                                    gevonden = false;
                                    break;
                                }
                            }
                            if (gevonden)
                            {
                                result.Add(w);
                            }
                        }
                    }
                    return result;

        ...

----


----
 public interface ILijstItems
    {
        public string Id { get; }
        public string ItemNaam { get; }
    }
----

Stel 



=== Herbruikbaar Datagrid

==== Doel
Het doel van het herbruikbaar datagrid is dat we elk model met één enkel datagrid kunnen gebruiken,
zodat we dit niet altijd opnieuw moeten definiëren.

==== Werking
Als we data willen tonen via een datagrid halen we eerst de data van de BL-Laag op, vervolgens wordt deze omgezet naar
een ViewModel Class die dan in het datagrid ingelezen kan worden.

*Voorbeeld* +
_Let op: De code is geformateerd er zijn grote delen uit de code gelaten voor de complexiteit te verminderen._ +
Hier is onze BL Bedrijf Class
[source, c#]
----
public class Bedrijf
    {
        public int Id { get; set; }
        public string Naam { get; set ; }
        public string Btw { get ; set ; }
        public string Adres { get ; set ; }
        public string Telefoon { get; set; }
        public string Email { get; set; }

        public Bedrijf(string naam, string btw, string adres, string telefoon, string email)
        {
            Naam = naam;
            Adres = adres;
            Btw = btw;
            Telefoon = telefoon;
            Email = email;
        }
    }
----

In de presentatie laag halen deze op via de bedrijfManger. En zetten deze om naar onze bedrijfView Models.
[source, c#]
----
ReadOnlyList<Bedrijf> bedrijven = _bedrijfManager.GeefAlleBedrijven();
foreach (Bedrijf bedrijf in bedrijven)
{
    BedrijfView bedrijfView = new BedrijfView(bedrijf);
    bedrijfView.PropertyChanged += UpdateBedrijf;
    _bedrijfViews.Add(bedrijfView);
}
----

----
public class BedrijfView : INotifyPropertyChanged
    {
        public Bedrijf Bedrijf;
        private string _naam;
        private string _btw;
        private string _adres;
        private string _telefoon;
        private string _email;

        public event PropertyChangedEventHandler? PropertyChanged;

        [Hoofding("Naam")]
        public string Naam { get; set; }

        [Hoofding("BTW-Nummer")]
        public string Btw { get; set; }

        [Hoofding("Adres")]
        public string Adres { get; set; }

        [Hoofding("Telefoon Nummer")]
        public string Telefoon { get; set; }

        [Hoofding("Email")]
        public string Email { get ; set;}

        public BedrijfView(Bedrijf bedrijf)
        {
            Bedrijf = bedrijf;
            Naam = bedrijf.Naam;
            Btw = bedrijf.Btw;
            Adres = bedrijf.Adres;
            Telefoon = bedrijf.Telefoon;
            Email = bedrijf.Email;

        }

        private void OnPropertyChanged(string name = null)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
            }
        }

----
Zoals je kan zien kunnen we bij de ViewModels ook de Hoofdging instellen. Hierdoor kan het datagrid de hoogding instellen
door gebruik te maken van *reflection*.

Nu alles klaar staat kunnen we dit model doorgeven aan het datagrid.
----
dataGrid.StelDataIn<BedrijfView>(_bedrijfViews);
----

Dit gebeurt er in het DataGrid.

----
public void StelDataIn<T>(IEnumerable viewModel, bool readOnly= false, IEnumerable extraInfo = null)
        {
            _data = viewModel;
            dataGrid.ItemsSource = null;
            MaakHoofding<T>(viewModel, extraInfo);
            dataGrid.ItemsSource = viewModel;
            dataGrid.IsReadOnly = readOnly;

        }

        private void MaakHoofding<T>(IEnumerable viewModel, IEnumerable extraInfo = null)
        {
            dataGrid.Columns.Clear();
            Dictionary<string, string> hoofding = HoofdingManager.GeefHoofding<T>();
            Dictionary<string, CellType> cellTypes = CellManager.GeefCellType<T>();
            foreach (string key in hoofding.Keys)
            {
                if (cellTypes.ContainsKey(key))
                {
                    DataGridComboBoxColumn dataGridComboBoxColumn = new DataGridComboBoxColumn();
                    dataGridComboBoxColumn.Header = hoofding[key];

                    dataGridComboBoxColumn.ItemsSource = extraInfo;
                    dataGridComboBoxColumn.TextBinding = new Binding(key);
                    dataGridComboBoxColumn.DisplayMemberPath = "Naam";
                    dataGridComboBoxColumn.SelectedValuePath = "Naam";
                    dataGrid.Columns.Add(dataGridComboBoxColumn);

                }
                else
                {
                    DataGridTextColumn c = new DataGridTextColumn();
                    c.Header = hoofding[key];
                    c.Binding = new Binding(key);
                    dataGrid.Columns.Add(c);
                }


            }
            dataGrid.AutoGenerateColumns = false;
        }

----

Vervolgens kan er aan de hand van een EventHandler een zoek method aan toegevoed worden die automatisch wordt opgeroepen
bij een verandering in de zoekbalk.
----
 private void zoekBar_TextChanged(object sender, TextChangedEventArgs e)
{
    // Hier kunnen we ons datagrid filter op het huidige zoekwoord.
    string zoekText = zoekBar.Text;
    OpDataFiltering.Invoke(sender, zoekText);

}
----


== Business (Diego, Tuur)

=== Class diagram

=== controle's (welke controle's, waarom hebben we een statishe class?)

=== DeBouncer
==== Doel
Het doel van de DeBouncer is om onnodige verkeer tussen de applicatie en de databank te voorkomen.
Stel we we willen een naam zoeken zonder een zoek knop te gebruiken. Er zal automatich gezocht worden via de zoekbalk.
Zonder de DeBouncer zou er bij elke verandering in de zoekbalk een request naar de databank gemaakt worden dat in principe
onnodig is. Door de DeBouncer te gebruiken kunnen we een interval instellen, het doel van dit interval is dat de zoekmethode pas
wordt uitgevoerd van zodra er geen nieuwe input meer binnen komt geduurende het interval.

==== Werking
Voor de DeBouncergebruikt kan worden moeten we eerst een instantie van het object maken, waarbij we het interval meegeven
als parameter. Dit interval zorgt er voor dat de De Bouncer wordt opgroepen, van zodra er geduurende dit intervaal geen nieuwe input binnen komt.
----
var debounceDispatcher = new DebounceDispatcher(1000);
----

----
 debounceDispatcher.Debounce(() =>
{
    ZoekMethode(zoekWoord);
});
----
Dit gebreurt er in de DeBouncer.
Hier wordt er een Task gemaakt waar onze zoek methode wordt ingestoken. Vervolgens geven we die taak door aan de DeBounceAsync().
----
public void Debounce(Action action)
{
    Func<Task<bool>> actionAsync = () => Task.Run(() =>
    {
        action.Invoke();
        return true;
    });

    DebounceAsync(actionAsync);
}

----